### PR TITLE
Fixes #27593 - Use openscap_parser to parse reports

### PR DESCRIPTION
**Pull request by xprazak2**
needs https://github.com/dLobatog/openscap_parser/pull/6

### CODE REVIEW

**Comment by xprazak2** [comment]
Needs https://github.com/OpenSCAP/openscap_parser/pull/30

**Comment by ares** [comment]
#30 is merged, not sure if we also need #6 but that's currently closed
needs rebase now

**Comment by xprazak2** [comment]
Rebased, we also parse score now.

**Review by ares — APPROVED** [review]
Thanks @xprazak2, merging!

**Pull request merged**
