### PR TITLE
Fixes #14801 - Encoding workaround for 1.8

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
LGTM :+1: not tested though.

**Comment by itmanagerro** [comment]
To be honest, it's exactly what I've used to fix in on my local, yes... it's fixing this particular issue. TESTED and Passed 👍  💯 
On the other hand, there are still a lot workarounds to find for Ruby 1.8.7
I'll need to get involved here 👍 

Now on https://domain.tld/compliance/policies/6/dashboard I get the following error.
`Oops, we're sorry but something went wrong 'nil' is not an ActiveModel-compatible object. It must implement :to_partial_path.`

**Comment by ares** [comment]
Thanks for testing @itmanagerro, merging. Thanks @xprazak2 for the fix.

Regarding the new issue, it seems to be in foreman_openscap. Note that foreman requires Ruby 1.9+ since 1.7.0, so Ruby 1.8 works only for smart_proxy_openscap. You can run Foreman on host with newer ruby but continue using smart proxy with smart_proxy_openscap on host with Ruby 1.8.

**Comment by shlomizadok** [comment]
@itmanagerro - Thanks for testing this.
As for other issues, let's solve them one at a time - please report via http://projects.theforeman.org/projects/smart-proxy-openscap :)

regarding the policy dashboard issue, it seems to be a foreman_openscap issue, rather then a smart_proxy_openscap issue. Will you file a detailed bug in http://projects.theforeman.org/projects/foreman_openscap/issues/new

Thanks a lot.
@ares - please ACK  - will merge

**Comment by shlomizadok** [comment]
Oh... Thanks @ares !! :smile:

**Pull request merged**
