### PR TITLE
Fixes #17464 - Use digest to detect scap_file changes

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by shlomizadok** [comment]
I assume https://github.com/theforeman/foreman_openscap/pull/232 is the corresponding PR on the foreman side? Is there a concern of changing the API URLs?

**Comment by xprazak2** [comment]
Maybe we could leave the old endpoint there with a deprecation message. Will make changes.

**Comment by shlomizadok** [comment]
@xprazak2 - not sure we need to leave the old endpoint if foreman_openscap is the only consumer. Just want to ensure that's the case :smile:

**Comment by xprazak2** [comment]
I am thinking about a case when someone updated foreman_openscap but not smart_proxy_openscap...

**Comment by xprazak2** [comment]
Updated, I kept the old endpoint with deprecation warning.

**Comment by ares** [comment]
> Updated, I kept the old endpoint with deprecation warning.

excellent, just please either open refactoring issue to remove it or add a version when we it will be removed to the warning/comment so we don't forget to remove it with major version bump

**Comment by shlomizadok** [comment]
@xprazak2 - rebase please :)

**Comment by ares** [comment]
Tested, works well. One related question in https://github.com/theforeman/foreman_openscap/pull/232

**Comment by ares** [comment]
Thanks @xprazak2, merging.

**Pull request merged**
