### PR TITLE
Fixes #18086 - Fix typo in smart-proxy-openscap-send

### PR DESCRIPTION
**Pull request by xprazak2**
:laughing: 
BTW, does anyone know why line 42 has `puts ` and not `logger`?

### CODE REVIEW

**Comment by ares** [comment]
Probably for users that runs the command manually? I guess debugging purposes.

**Comment by ares** [comment]
Thanks @xprazak2, would you mind creating a redmine issue and linked the commit via it's message?

**Comment by xprazak2** [comment]
I created a ticket and updated commit message

**Comment by shlomizadok** [comment]
Thanks @xprazak2 - merging :)

**Pull request merged**
