### PR TITLE
Fixes #27017 - Use openscap_parser for profiles

### PR DESCRIPTION
**Pull request by xprazak2**
~~TODO: tests~~

needs https://github.com/dLobatog/openscap_parser/pull/1

### CODE REVIEW

**Comment by xprazak2** [comment]
packaging: https://github.com/theforeman/foreman-packaging/pull/3853

**Comment by xprazak2** [comment]
Failing on ruby 2.0 :(

**Comment by ares** [comment]
Seems like that's due to safe navigation operator. Perhaps we could avoid using it in the parser?

**Comment by xprazak2** [comment]
I opened https://github.com/dLobatog/openscap_parser/pull/2 to fix it.

**Comment by akofink** [comment]
This is going to need an update after https://github.com/dLobatog/openscap_parser/pull/19

**Comment by xprazak2** [comment]
Rebased, now using openscap_parser 1.0.0

**Comment by xprazak2** [comment]
[test smart_proxy_openscap]

**Comment by xprazak2** [comment]
packaging: https://github.com/theforeman/foreman-packaging/pull/4415

**Comment by xprazak2** [comment]
https://github.com/OpenSCAP/openscap_parser/pull/24 to fix tests

**Comment by xprazak2** [comment]
Green, at last.

**Comment by ares** [comment]
Thanks @xprazak2, verified I'm getting the same results! Merging.

**Pull request merged**
