### PR TITLE
Fixes #31040 - Process and parse OVAL reports

### PR DESCRIPTION
**Pull request by xprazak2**
These changes allow proxy to receive OVAL report from client and parse the incoming XML file. For now, it just dumps the json into a report storage - it does not keep the original XML.

Needs pending PRs for openscap parser to work and also tests

### CODE REVIEW

**Comment by ares** [comment]
I have applied https://github.com/OpenSCAP/openscap_parser/pull/32 to my openscap_parser, and with patch foreman_scap_client, I'm getting 

```ruby
2020-11-16 17:59:55 - NoMethodError - undefined method `definition_results' for #<OpenscapParser::OvalReport:0x000056199509dee0>
Did you mean?  definitions:
        /home/ares/Projekty/Zdrojaky/smart_proxy_openscap/lib/smart_proxy_openscap/oval_report_parser.rb:29:in `parse_report'
        /home/ares/Projekty/Zdrojaky/smart_proxy_openscap/lib/smart_proxy_openscap/oval_report_parser.rb:21:in `as_json'
        /home/ares/Projekty/Zdrojaky/smart_proxy_openscap/lib/smart_proxy_openscap/openscap_api.rb:69:in `block in <class:Api>'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
        /home/ares/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
        /home/ares/Projekty/Zdrojaky/smart-proxy/lib/proxy/log.rb:103:in `call'
```

**Comment by xprazak2** [comment]
Do you have https://github.com/OpenSCAP/openscap_parser/pull/31 as well?

**Comment by ares** [comment]
Ah please ignore me, that was PEBKAC. I updated my Gemfile on smart proxy instead of smart_proxy_openscap now :-)

**Comment by xprazak2** [comment]
Changes:
* proxy is now able to serve oval content to clients
* proxy parses incoming data from client and sends a list of CVEs to foreman. Right now, nothing is stored on proxy - not even in spool if the upload fails.

I pluralized resource name in upload path, update to client is needed for testing.

**Comment by ares** [comment]
needs a little rebase now :-)

**Comment by xprazak2** [comment]
Rebased.

**Review by ares — APPROVED** [review]
Works fine, no need to wait any longer, ready for merge!

**Comment by ares** [comment]
Probably worth a major version bump. Anyway, merging, thanks @xprazak2

**Pull request merged**
