### PR TITLE
Fixes #14462 - Add ability to use local Gemfiles

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by shlomizadok** [comment]
@cpeters - thanks for this pull request. 
We are trying to become a little bit more organized with the OpenSCAP plugins and document everything at Foreman's Redmine tracker.
Will you kindly add an issue at [smart_proxy_openscap tracker](http://projects.theforeman.org/projects/smart-proxy-openscap/issues/new) ?
Thanks and sorry for the hustle.

**Comment by cpeters** [comment]
@shlomizadok Updated

**Comment by cpeters** [comment]
@shlomizadok Stephen raised a question of whether or not we should be consistent with Foreman instead of the Hammer plugins. https://github.com/theforeman/smart_proxy_dynflow/pull/14#issuecomment-205376185

**Comment by shlomizadok** [comment]
@cpeters - Foreman style (bundler.d/Gemfile.local) here too please. Thanks

**Comment by cpeters** [comment]
@shlomizadok We ran into an issue. https://github.com/theforeman/smart_proxy_dynflow/pull/14#issuecomment-205402334

smart_proxy_openscap is doing something similar in the spec

https://github.com/theforeman/foreman-packaging/blob/rpm/develop/rubygem-smart_proxy_openscap/rubygem-smart_proxy_openscap.spec#L71

**Comment by cpeters** [comment]
@shlomizadok Updating to make consistent with `smart_proxy_dynflow`

https://github.com/theforeman/smart_proxy_dynflow/pull/14

**Comment by shlomizadok** [comment]
Thanks a lot @cpeters ! Merging

**Pull request merged**
